#include "scanner.h"
int parser();
 int START ();
int FUNC ();
int FORWAR ();
int ARG ();
int ARGDAL ();
int CYKLUS ();
int KDYZ ();
int ELSEP ();
int SEKVENCE ();
int POKYN ();
int SLOZ ();
int PRVNI ();
int DALSI ();
int PRIKAZ ();
int DEK ();
int DEKDAL ();
int TYPE ();
int BOOLEANP ();
int VYPIS ();
int DVYPIS ();
int GLOBDEK ();
int GLOBDEKDAL ();
int VYRAZ();
int gtoken(FILE *F, SToken *token );
